// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc24un8EHAhEOHq9p2N8TZ3WE0e5iWzYI',
    appId: '1:1038745400119:web:c259405caa7cfc3b6de0b2',
    messagingSenderId: '1038745400119',
    projectId: 'paindatabase-9f08d',
    authDomain: 'paindatabase-9f08d.firebaseapp.com',
    databaseURL: 'https://paindatabase-9f08d-default-rtdb.firebaseio.com',
    storageBucket: 'paindatabase-9f08d.appspot.com',
    measurementId: 'G-LSJSY0D3MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZATFUQIlnYXujAsO8KtASZJuTOdfoLuw',
    appId: '1:604634671998:android:cd6318dbdcd52d9a7b612f',
    messagingSenderId: '604634671998',
    projectId: 'boundfit-f941c',
    databaseURL: 'https://boundfit-f941c-default-rtdb.firebaseio.com',
    storageBucket: 'boundfit-f941c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx9yrGprF-GcyMfUsfy4aeZTG6wATIzmw',
    appId: '1:1038745400119:ios:b8036f7840aa6b4e6de0b2',
    messagingSenderId: '1038745400119',
    projectId: 'paindatabase-9f08d',
    databaseURL: 'https://paindatabase-9f08d-default-rtdb.firebaseio.com',
    storageBucket: 'paindatabase-9f08d.appspot.com',
    iosClientId: '1038745400119-pv0avukf0itnm2egb3r5snhb2ae3er3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.pain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx9yrGprF-GcyMfUsfy4aeZTG6wATIzmw',
    appId: '1:1038745400119:ios:b8036f7840aa6b4e6de0b2',
    messagingSenderId: '1038745400119',
    projectId: 'paindatabase-9f08d',
    databaseURL: 'https://paindatabase-9f08d-default-rtdb.firebaseio.com',
    storageBucket: 'paindatabase-9f08d.appspot.com',
    iosClientId: '1038745400119-pv0avukf0itnm2egb3r5snhb2ae3er3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.pain',
  );
}
